### ISSUE TITLE
[GCB] Improve GCB verification tracking issue

### ISSUE THREAD

**Issue by asraa** [slsa-framework/example-package#149]
This issue tracks action items left for GCB verification support.

Currently, the workflows run on two schedules, a biweekly one and a daily one. The biweekly one triggers a build, while the daily one retrieves the latest build from that image and verifies it.  

- [ ] Add freshness check on build - in case the builds fail, detect that from the verifiers
- [ ] Add provenance content verification to the payload: https://github.com/slsa-framework/example-package/blob/main/.github/workflows/scripts/e2e.gcb.default.verify.sh#L19
- [ ] Investigate 1st generation and 2nd generation repository generation 
![image](https://user-images.githubusercontent.com/5194569/224052039-46a72f4e-7985-426b-a15c-62cb7a5fc69a.png)
- [ ] Add non-annotated tag push. 

Currently, we test:
* [Annotated Tag push](https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.gcb.tag.main.annotated-build.slsa3.yml) 
* [Push to main](https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.gcb.push.main.default.slsa3.yml)

Things to note:
* We [cannot](https://github.com/slsa-framework/slsa-verifier/blob/5a77b25fb4e7e0490847dbbd3ce6cddf479b15da/verifiers/internal/gcb/provenance.go#L396) test branch or tag options in the slsa-verifier for GCB - we only test that we can verify these triggers - so there doesn't seem to be a point in testing `branch1`. Tag verification is skipped because we aren't verifying on [GITHUB_REF_TYPE](https://github.com/slsa-framework/example-package/blob/0a7ae92895b0d21794cbcc9ce97d7893fb14a7d8/.github/workflows/scripts/e2e-verify.common.sh#L316) tag (we build on tag, but verify on daily [schedule](https://github.com/slsa-framework/example-package/blob/0a7ae92895b0d21794cbcc9ce97d7893fb14a7d8/.github/workflows/e2e.gcb.tag.main.annotated-build.slsa3.yml#L84))
* Some workflows do not rebuilds on workflow_dispatch to prevent overbuilding. Consider an input here, like [this](https://github.com/slsa-framework/example-package/blob/main/.github/workflows/e2e.gcb.push.main.default.slsa3.yml#L9) - on the other hand, you can manually trigger builds by clicking RUN on the trigger [page](https://pantheon.corp.google.com/cloud-build/triggers;region=us-west2?project=slsa-tooling)
* Only push to branch and tag are supported for GitHub repository triggers in GCB.

cc @laurentsimon @ianlewis

**Comment by laurentsimon** [comment]
Do you know what 1st vs 2nd source generation is?

**Comment by asraa** [comment]
> Do you know what 1st vs 2nd source generation is?

Not really, there are some docs. https://cloud.google.com/build/docs/repositories

It seems like its more about the way that the connection is done (through GitHub Apps or auth?)
